"""Migration drafter.

Turns a classified ``DriftEvent`` (+ its ``ImpactSet``) into a
``MigrationBundle`` — the bundle of files, PR title/body, and labels the
PR Gateway will ship to GitHub.

Day-3 scope
-----------
* ``COLUMN_ADDED_NULLABLE`` only.
* Patch is a formatting-preserving edit of ``models/sources.yml``
  (ruamel.yaml round-trip), adding the new column with a placeholder
  description so reviewers can fill it in.
* PR body rendered via a Jinja template (string, not a file) so we can
  unit-test the output without filesystem fixtures.

NO LLM here yet. Week 4 swaps the deterministic SQL/YAML patcher for
Instructor + Claude when ``--use-llm`` is set; the fallback path stays
rules-only for cost and audit reasons.
"""

from __future__ import annotations

import io
from pathlib import Path

from jinja2 import Environment, StrictUndefined
from ruamel.yaml import YAML

from schema_drift.models import (
    ChangeType,
    DriftEvent,
    FilePatch,
    ImpactSet,
    MigrationBundle,
)

# ---------------------------------------------------------------------------
# Jinja environment (autoescape off — we're writing markdown, not HTML)
# ---------------------------------------------------------------------------

_env = Environment(
    autoescape=False,
    undefined=StrictUndefined,
    trim_blocks=True,
    lstrip_blocks=True,
    keep_trailing_newline=True,
)

_PR_BODY_TEMPLATE = _env.from_string(
    """\
## 🚨 Schema drift detected

**Source:** `{{ event.source_identifier }}`
**Change:** `{{ event.change_type.value }}`
**Severity:** **{{ event.severity.value | upper }}**
**Auto-mergeable:** {{ "yes" if event.auto_mergeable else "no (human review required)" }}
**Confidence:** {{ "%.2f" | format(event.confidence) }}

### What changed
{% if event.column_after %}
A new column `{{ event.column_after.name }}` (`{{ event.column_after.data_type }}`, \
nullable={{ event.column_after.nullable }}) was added to \
`{{ event.column_after_table }}`.
{% else %}
See `raw_changes` in the audit trail.
{% endif %}

### Downstream impact
{% if impact.dbt_models %}
**dbt models touched ({{ impact.dbt_models | length }}):**
{% for m in impact.dbt_models %}
- `{{ m }}`
{% endfor %}
{% else %}
_No downstream dbt models detected._
{% endif %}

{% if impact.dashboards %}
**Dashboards potentially affected:**
{% for d in impact.dashboards %}
- [{{ d.tier | upper }}] {{ d.tool }}/{{ d.name }}
{% endfor %}
{% endif %}

**Blast-radius score:** `{{ "%.1f" | format(impact.blast_radius_score) }}` \
(lineage confidence: `{{ impact.lineage_confidence }}`)

### Proposed change
This PR patches `models/sources.yml` so dbt's source freshness + tests pick up
the new column. No model SQL changes were generated automatically because the
column is nullable and additive (safe by construction).

### Reviewer checklist
- [ ] Fill in a meaningful `description:` for the new column.
- [ ] Decide whether `not_null` / `unique` data tests apply.
- [ ] Confirm no PII implications.
- [ ] Backfill plan (if any) — N/A for nullable additive columns.

---

<sub>Generated by `schema-drift-detective` from drift event \
`{{ event.id }}` detected at `{{ event.detected_at.isoformat() }}`.</sub>
"""
)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


class MigrationDrafter:
    """Produce a ``MigrationBundle`` for one ``DriftEvent``.

    Parameters
    ----------
    dbt_project_dir
        Repo-relative path to the dbt project root (the directory containing
        ``dbt_project.yml``).
    sources_yml_relpath
        Path to the ``sources.yml`` to patch, relative to ``dbt_project_dir``.
        Defaults to ``"models/sources.yml"`` to match the demo layout.
    """

    def __init__(
        self,
        dbt_project_dir: str | Path = "dbt_project",
        *,
        sources_yml_relpath: str | Path = "models/sources.yml",
    ) -> None:
        self.dbt_project_dir = Path(dbt_project_dir)
        self.sources_yml_relpath = Path(sources_yml_relpath)

    # ------------------------------------------------------------------ entry

    def draft(self, event: DriftEvent, impact: ImpactSet) -> MigrationBundle:
        """Build a ``MigrationBundle`` for the supplied event.

        Day-3: only ``COLUMN_ADDED_NULLABLE`` is supported. Any other change
        type raises ``NotImplementedError`` so callers fail loud instead of
        silently shipping an empty PR. Days 4-7 expand coverage.
        """
        if event.change_type is not ChangeType.COLUMN_ADDED_NULLABLE:
            raise NotImplementedError(
                f"MigrationDrafter (Day-3) only handles COLUMN_ADDED_NULLABLE; "
                f"got {event.change_type.value!r}"
            )
        if event.column_after is None:  # defensive: classifier guarantees this
            raise ValueError("COLUMN_ADDED_NULLABLE event has no column_after")

        table_ident, new_col_name = self._split_source_identifier(event.source_identifier)
        patched_yaml = self._patch_sources_yml(
            table_ident=table_ident,
            new_column_name=new_col_name,
        )

        sources_path = self.dbt_project_dir / self.sources_yml_relpath
        file_patch = FilePatch(
            path=str(sources_path).replace("\\", "/"),
            content=patched_yaml,
            mode="update",
        )

        pr_title = self._pr_title(event)
        pr_body = self._render_pr_body(event=event, impact=impact, table_ident=table_ident)
        branch_name = f"drift/{event.id.lower()}"

        return MigrationBundle(
            drift_event_id=event.id,
            branch_name=branch_name,
            pr_title=pr_title,
            pr_body_markdown=pr_body,
            files=(file_patch,),
            rollback_sql=None,
            backfill_sql=None,
            labels=("schema-drift", f"severity:{event.severity.value}"),
            is_draft=True,
        )

    # --------------------------------------------------------------- internals

    @staticmethod
    def _split_source_identifier(source_identifier: str) -> tuple[str, str]:
        """Split ``schema.table.column`` into (``schema.table``, ``column``)."""
        parts = source_identifier.split(".")
        if len(parts) < 3:
            raise ValueError(
                f"source_identifier {source_identifier!r} must be 'schema.table.column'"
            )
        return ".".join(parts[:-1]), parts[-1]

    @staticmethod
    def _pr_title(event: DriftEvent) -> str:
        table_ident, col_name = MigrationDrafter._split_source_identifier(event.source_identifier)
        return f"[schema-drift] Add nullable column `{col_name}` to `{table_ident}`"

    def _render_pr_body(
        self,
        *,
        event: DriftEvent,
        impact: ImpactSet,
        table_ident: str,
    ) -> str:
        # Bind table_ident onto a thin object so the template can reach it.
        ctx = {
            "event": _EventCtx(event=event, table_ident=table_ident),
            "impact": impact,
        }
        return _PR_BODY_TEMPLATE.render(**ctx)

    def _patch_sources_yml(self, *, table_ident: str, new_column_name: str) -> str:
        """Round-trip ``sources.yml`` adding ``new_column_name`` under the right table.

        Uses ruamel.yaml to preserve comments, key order, and indentation.
        """
        path = self.dbt_project_dir / self.sources_yml_relpath
        yaml = YAML()
        yaml.preserve_quotes = True
        yaml.indent(mapping=2, sequence=4, offset=2)

        with path.open("r", encoding="utf-8") as f:
            doc = yaml.load(f)

        # source_identifier is "schema.table"; sources.yml indexes by source `schema`
        # and table `name`.
        schema_name, table_name = table_ident.split(".", 1)

        target_table = self._locate_table(doc, schema_name=schema_name, table_name=table_name)
        if target_table is None:
            raise ValueError(
                f"sources.yml does not declare {schema_name}.{table_name} — cannot patch."
            )

        columns = target_table.setdefault("columns", [])
        existing_names = {c.get("name") for c in columns if isinstance(c, dict)}
        if new_column_name in existing_names:
            # Idempotent: don't double-add. Useful for re-runs of the demo.
            return self._dump(yaml, doc)

        columns.append(
            {
                "name": new_column_name,
                "description": "TODO(reviewer): describe this newly-detected column.",
            }
        )
        return self._dump(yaml, doc)

    @staticmethod
    def _locate_table(doc: dict, *, schema_name: str, table_name: str) -> dict | None:
        for src in doc.get("sources", []) or []:
            # Match either source `name` or explicit `schema` key.
            src_schema = src.get("schema", src.get("name"))
            if src_schema != schema_name:
                continue
            for tbl in src.get("tables", []) or []:
                if tbl.get("name") == table_name:
                    return tbl
        return None

    @staticmethod
    def _dump(yaml: YAML, doc: dict) -> str:
        buf = io.StringIO()
        yaml.dump(doc, buf)
        return buf.getvalue()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


class _EventCtx:
    """Tiny adapter exposing the few fields the Jinja template needs.

    Keeps the template free of conditionals around optional pydantic fields.
    """

    __slots__ = ("_event", "column_after_table")

    def __init__(self, *, event: DriftEvent, table_ident: str) -> None:
        self._event = event
        self.column_after_table = table_ident

    def __getattr__(self, name: str):
        return getattr(self._event, name)


__all__ = ["MigrationDrafter"]
