"""Opt-in live integration test against ``drift-demo-sandbox``.

Auto-skipped unless **all** of these are set:

* ``DRIFT_LIVE_PR=1``
* ``DRIFT_GITHUB_TOKEN=<PAT scoped to drift-demo-sandbox>``
* ``DRIFT_GITHUB_REPO=AntarangSharma/drift-demo-sandbox`` (or any sandbox)

Run with::

    DRIFT_LIVE_PR=1 \
    DRIFT_GITHUB_TOKEN=ghp_xxx \
    DRIFT_GITHUB_REPO=AntarangSharma/drift-demo-sandbox \
    pytest -m live tests/test_pr_live.py

This will open a real PR. We don't clean it up automatically — that's a
manual step (or a Day-6 chore). Each invocation uses a ULID branch name
so re-runs don't collide.

The point of this test is *not* CI coverage. It's a single, reproducible
recipe that you can re-run to prove the live path still works after every
PyGithub upgrade.
"""

from __future__ import annotations

import os

import pytest
from ulid import ULID

from schema_drift.models import FilePatch, MigrationBundle
from schema_drift.pr import GitHubPRGateway

_REQUIRED_ENV = ("DRIFT_LIVE_PR", "DRIFT_GITHUB_TOKEN", "DRIFT_GITHUB_REPO")

_missing = [name for name in _REQUIRED_ENV if not os.environ.get(name)]

pytestmark = [
    pytest.mark.live,
    pytest.mark.skipif(
        bool(_missing),
        reason=f"live PR test needs env vars {_missing}",
    ),
]


def test_opens_real_pr_against_sandbox() -> None:
    repo_slug = os.environ["DRIFT_GITHUB_REPO"]
    token = os.environ["DRIFT_GITHUB_TOKEN"]

    # Unique branch per run — prevents the idempotency-skip from triggering
    # on the second invocation.
    branch_suffix = str(ULID()).lower()
    bundle = MigrationBundle(
        drift_event_id=f"live-test-{branch_suffix}",
        branch_name=f"drift/live-test-{branch_suffix}",
        pr_title="[live-test] sentinel patch — safe to close",
        pr_body_markdown=(
            "## Live integration test\n\n"
            "This PR was opened by the `test_opens_real_pr_against_sandbox` "
            "test in `tests/test_pr_live.py`. It exists purely to prove the "
            "live path still works end-to-end. Close it unmerged when you see it.\n"
        ),
        files=(
            FilePatch(
                path=f"agent-sentinels/{branch_suffix}.md",
                content=(
                    "# sentinel\n\nGenerated by the schema-drift agent live integration test.\n"
                ),
                mode="create",
            ),
        ),
        labels=("schema-drift", "live-test"),
        is_draft=True,
    )

    gateway = GitHubPRGateway(repo=repo_slug, token=token)
    result = gateway.open_pr(bundle, dry_run=False)

    assert result.dry_run is False
    assert result.url is not None
    assert result.url.startswith(f"https://github.com/{repo_slug}/pull/")
    assert result.branch == bundle.branch_name
    assert result.skipped_reason is None
